DROP table IF EXISTS keep_alive;
CREATE TABLE keep_alive (
  `ts` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `partition_key` smallint(6) generated always as (hour(ts)),
  `route_names` varchar(8192) NOT NULL,
  `pid` bigint(20) NOT NULL,
  `app` varchar(255) NOT NULL,
  `process_cpu` float DEFAULT NULL,
  `process_memory` float DEFAULT NULL,
  `process_uptime` float DEFAULT NULL,
  `node_version` varchar(255) DEFAULT NULL,
  `pck_version` varchar(255) DEFAULT NULL,
  `os_total_memory` bigint(20) DEFAULT NULL,
  `os_free_memory` bigint(20) DEFAULT NULL,
  `os_cpus` smallint(6) DEFAULT NULL,
  `os_load0` float DEFAULT NULL,
  `os_load1` float DEFAULT NULL,
  `os_load2` float DEFAULT NULL,
  `os_uptime` bigint(20) DEFAULT NULL,
  KEY `keep_alive_ts_idx` (`ts`)
) ENGINE=InnoDB AUTO_INCREMENT=8001 DEFAULT CHARSET=utf8;
alter table keep_alive partition by list(partition_key) (
   partition congruent_remainder0 values in (0),
   partition congruent_remainder1 values in (1),
   partition congruent_remainder2 values in (2),
   partition congruent_remainder3 values in (3),
   partition congruent_remainder4 values in (4),
   partition congruent_remainder5 values in (5),
   partition congruent_remainder6 values in (6),
   partition congruent_remainder7 values in (7),
   partition congruent_remainder8 values in (8),
   partition congruent_remainder9 values in (9),
   partition congruent_remainder10 values in (10),
   partition congruent_remainder11 values in (11),
   partition congruent_remainder12 values in (12),
   partition congruent_remainder13 values in (13),
   partition congruent_remainder14 values in (14),
   partition congruent_remainder15 values in (15),
   partition congruent_remainder16 values in (16),
   partition congruent_remainder17 values in (17),
   partition congruent_remainder18 values in (18),
   partition congruent_remainder19 values in (19),
   partition congruent_remainder20 values in (20),
   partition congruent_remainder21 values in (21),
   partition congruent_remainder22 values in (22),
   partition congruent_remainder23 values in (23)
);